FROM alpine:latest

# SQLiteをインストール
RUN apk add --no-cache bash sqlite

# 作業ディレクトリを設定
WORKDIR /app

# マイグレーションスクリプトとファイルをコピー
COPY scripts/migrate.sh /app/migrate.sh
COPY migrations /app/migrations

# スクリプトに実行権限を付与
RUN chmod +x /app/migrate.sh

# マイグレーション実行
ENTRYPOINT ["/app/migrate.sh"]
CMD ["up"]
